### ISSUE TITLE
What happened to DirectImportField?

### ISSUE THREAD

**Issue by larsrinn** [seddonym/import-linter#107]
In 1.2.5 a custom contract (to prohibit relative imports) is failing, because we're referencing `fields.DirectImportField` which doesn't seem to exist anymore. However, the changelog doesn't tell anything about it. What happened to it and what would be the replacement we should use?

**Comment by seddonym** [comment]
Hi @larsrinn - apologies for breaking your contract! You should just be able to replace `DirectImportField` with `ImportExpressionField`. The reason for this change is because, with the addition of wildcards, imports listed in contracts don't necessarily need to correspond one-to-one with an actual import, they could refer to sets of imports.

In retrospect it may have been better to deprecate `DirectImportField` instead, for backward compatibility - sorry about that. Let me know if it works for you and I'll update the changelog accordingly.

I'd also be interested to know how you're using custom contracts, so I can better support changes in the future.

**Comment by seddonym** [comment]
Oh, also, if you were using `helpers.pop_imports` you should now use `helpers.pop_import_expressions`, as per [this example](https://github.com/seddonym/import-linter/blob/67a77073414c6f52cd519ab587cf3240409a6ffe/src/importlinter/contracts/forbidden.py#L34).

**Comment by Joerg-Tech** [comment]
With your suggestions it's working again, thanks a lot @seddonym !

**Comment by seddonym** [comment]
Good to hear! I'm going to close this issue.
