### ISSUE TITLE
Use stdlib tomllib package on Python 3.11

### ISSUE THREAD

**Issue by djmattyg007** [seddonym/import-linter#146]
There's no need to use a third party package for reading TOML files on Python 3.11, so it would be nice to avoid the additional dependency.

**Comment by seddonym** [comment]
Great idea! Happy to consider pull requests for this (the submitter will probably need to have a decent understanding of tox). Otherwise I'll probably get around to it at some point.

**Comment by mwgamble** [comment]
@seddonym How would you feel about moving away from the `toml` library for older versions of Python? `tomli` and `tomlkit` are both much more active and have better support. Most Python projects have made the switch.

**Comment by seddonym** [comment]
> How would you feel about moving away from the toml library for older versions of Python?

I don't have any particular attachment to that library, though equally I haven't experienced any problems with it either. I guess I would say that in the absence of any problems, maybe there are more worthwhile things to spend time on, but certainly open to being persuaded otherwise.

**Comment by djmattyg007** [comment]
The stdlib package `tomllib` comes from the third party package `tomli`. This means they have the same interface, so switching makes sense if there's no other reason to stay.

**Comment by mwgamble** [comment]
`tomli` is what's [used by coverage](https://github.com/nedbat/coveragepy/blob/3823cc6d41956d0b8cfb55d6151673017a825c49/setup.py#L119-L122), so it makes sense to use the same thing.

**Comment by mwgamble** [comment]
@seddonym How would you feel about making `tomli` a compulsory dependency (restricted to Python versions older than 3.11)?

It could help simplify things:

- We wouldn't need markers for the tests
- End users wouldn't need to worry about installing extra packages to start using it

Most users probably already have `tomli` installed anyway, because it's a compulsory dependency of other major packages such as `black`, `mypy`, `pytest`, `pylint` and `coverage`. Also, I'm struggling to get the type-checking working with `tomli` being an optional dependency :(

**Comment by mwgamble** [comment]
I've created #152, which switches to `tomllib` and `tomli` on older versions of Python. It makes `tomli` a compulsory dependency, because it's likely that users already have it installed anyway.
