### ISSUE TITLE
Consider dropping Click as a dependency

### ISSUE THREAD

**Issue by mwgamble** [seddonym/import-linter#149]
The CLI code in this package is relatively trivial. There are no subcommands, and most of the time there's no need to supply any arguments or flags either.

In order to avoid unnecessary dependencies and potential dependency conflicts when this package is installed in a bigger project, it may be prudent to re-implement the CLI using the standard library `argparse` package.

**Comment by seddonym** [comment]
Thanks for raising.

There are a couple of other reasons to keep Click:

- Import Linter also uses click for formatting: https://github.com/seddonym/import-linter/blob/master/src/importlinter/adapters/printing.py#L16
- At some point we might want to improve the output, in particular by showing [a progress bar](https://click.palletsprojects.com/en/8.1.x/utils/#showing-progress-bars).

For these reasons I'd be inclined to leave it as-is for the time being, but I could be persuaded otherwise...

**Comment by seddonym** [comment]
I'm going to close this as I'm unlikely to want to move away from Click.
