### ISSUE TITLE
The Settings class isn't friendly to IDE navigation

### ISSUE THREAD

**Issue by mwgamble** [seddonym/import-linter#151]
In PyCharm, I can't Ctrl+Click `settings.FILE_SYSTEM` because it doesn't actually exist. It's all dynamic, so PyCharm has no idea how to tell that it should actually point at something in `configuration.py`. If PyCharm can't work it out, I wonder if mypy would also be having a hard time with it.

**Comment by seddonym** [comment]
Thanks for raising - you're right, this is a drawback of the dynamic binding approach I've taken, which comes with other benefits relating to swappable dependencies and following the Dependency Inversion Principle.

I don't see it as a priority to address this for IDEs, partly because I'm not sure if there is a good way to do it, and partly because I don't think it's enough of a problem. If you have a concrete suggestion of how to improve it feel free to suggest though.

PS The type checking issue might be a bit more worthwhile to address, possibly with a mypy plugin, but with limited time I don't think this is likely to be worth the effort.

**Comment by mwgamble** [comment]
My recommendation would be to utilise proper dependency injection. Right now the settings object is a classic problematic service locator. This is a good enough explanation on the difference:

https://stackoverflow.com/questions/1557781/whats-the-difference-between-the-dependency-injection-and-service-locator-patte

This is also a decent breakdown of the problems with a service locator:

https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/

An interim alternative would be to replace `Settings.__getattr__` with dedicated `@property` methods for each of the expected properties. I'm sure it's not quite as straightforward as that, but it would potentially reduce the need to refactor other code.

I don't think a mypy plugin is a good idea. I would only reach for a mypy plugin for when there is an actual need for some dynamic code with no way around it. There are ways around it here, they just require some refactoring. The code isn't dynamic, just not written in a way that makes typing easy.

**Comment by seddonym** [comment]
Thanks for the recommendation, I think I'm going to stick with service locator for now despite its shortcomings. I prefer it to DI if the dependencies don't change at runtime as it avoids having to pass dependencies around so much, but I do appreciate it's not to everyone's taste.

It's essentially the same pattern as the Django settings framework which I have always enjoyed working with.

You might be interested in [this blog post](https://seddonym.me/2019/08/03/ioc-techniques/) I wrote on the subject.
