### ISSUE TITLE
Support for multiple packages within a single directory

### ISSUE THREAD

**Issue by kurtgn** [seddonym/import-linter#43]
hey,
thanks for the package, this is really what I need for my project!

There's one thing I don't get though. What if I want to enfoce import rules at the root of my project, not at one of its modules?

For example, I have a django project with a `core` module with some utilities and an `apps` module with several django apps. Is there a way to prohibit anything from the `apps` module to import the `core` module? What should be placed in the `root_package` setting then?

**Comment by user37596** [comment]
This is exactly what I was thinking too. Haven't figured out how to do it. I hope this will become possible.

**Comment by seddonym** [comment]
Hi, thanks for this, and sorry for the delay - I didn't realise I wasn't getting notifications on this repo so I've only just saw this.

I'm guessing from your question that you have a project with the following structure:

```
myproject/
    # Note: no __init__.py file, this is just a plain old directory.
    core/
        __init__.py
        utils.py
    apps/
        __init__.py
        foo/
             __init__.py
             urls.py
             views.py
             models.py
        bar/
             __init__.py
             urls.py
             views.py
             models.py
```
Let's say you want to prevent anything from `apps` importing from `core`. The way to approach this is using the [layers](https://import-linter.readthedocs.io/en/latest/contract_types.html#layers) contract type. Your project would contain two layers, `core` being the higher layer and `apps` being lower.

However, there is a bit of a snag with your project setup that you would need to sort out first. Import Linter analyses the imports within a single package. In the example above, `myproject` is not a package (as there is no `__init__.py` file), instead you have two separate packages in the current working directory. I would recommend adjusting this so that your Django project runs in a single package. Your imports would change from `from apps.bar import models` to `from myproject.apps.bar import models` but that can be achieved quickly with search and replace.

Once you've made your project a single package, it will work from the current directory - providing you're running `lint-imports` from a directory that you can also import your root package (`myproject`) from.

If you really don't want to have a single package as your project, you should be able to achieve this by treating `apps` as the `root_package` and `core` as an external package - but that's currently a bit more complicated as you would need to write a custom contract type that forbids imports from specific external packages. (I'll be adding a new contract type at some point that allows this.)  I would recommend the single package approach though.

If you are still stuck, please reply with an outline of your project directories, plus your .importlinter file, and I'll try to help.

**Comment by QasimK** [comment]
@seddonym I was looking at how to implement this as a custom contract type. I am wondering whether it is even possible at the moment without modifying other parts of the project?

If I set one of the package randomly as the root package, I get "Module X does not exist", where X is another top-level package in my project. If I attempt to set `root_package=` or remove the line, I get errors about the root package not existing, or being unable to read the configuration.

**Comment by seddonym** [comment]
Hi @QasimK, you've got two choices here.

Your first option is to turn the separate packages into a single package, by adding an __init__,py file under myproject. Import Linter will then analyse everything within myproject and you can probably just use the existing built in contracts.

Your second option is to pick one of the packages as the one that you want to analyse. In this case it would probably be `sharedcode`. You'd set that as the root package, and you'd also set `include_external_packages = True` (see [docs](https://import-linter.readthedocs.io/en/latest/usage.html#top-level-configuration)). This would then include references to service1 and service2 in the import graph (if they are imported) and you could then make a custom contract type to check they're not imported. This would be pretty straightforward, something along the lines of the ForbiddenImportContract used as an example in the [docs](https://import-linter.readthedocs.io/en/latest/custom_contract_types.html#step-one-implementing-a-contract-class).

If you're feeling patient, at some point soon I'll add this contract type as a built in anyway.

The disadvantage with the external packages approach is that it won't analyse anything within service1 or service2, but perhaps you don't mind about that.

Let me know how you get on!

**Comment by SemMulder** [comment]
I'm also running into this. Can we not just make `root_package` be a list (e.g. `root_packages`) instead? I can look into this if you want?

**Comment by seddonym** [comment]
Hi Sem,

Thanks for your comment, sorry for the delay in responding (I was on holiday).

I'm inclined to think you're right. Until recently I had seen this approach as being a nonstandard way to organise Python code bases but it's much commoner than I had appreciated.

It's a fair amount of work to achieve this, as it involves rethinking the foundations of Grimp, which is the library that builds the dependency graph that Import Linter analyses. I've created an issue there for the time being: https://github.com/seddonym/grimp/issues/62

**Comment by cybojenix** [comment]
A workaround I'm using for testing is having each module contain an `.importlinter` file, which I can iterate over.
It doesn't allow for having them in the same place, but does happen to logically group contracts.

My usecase is to keep the server code away from the library code, while also be able to enforce internal rules for each of the library code, and the server code.
```ini
# ulama/.importlinter
[importlinter:contract:1]
name = Prevent Library code from relying on server implementation
type = forbidden
source_modules =
    ulama
forbidden_modules = 
    ulama_server
    flask

# ulama_server/.importlinter
...
```
```mk
LAYER_LINT_CONFIGS = $(wildcard */.importlinter)
.PHONY: layer-lint $(LAYER_LINT_CONFIGS)
layer-lint: $(LAYER_LINT_CONFIGS)
$(LAYER_LINT_CONFIGS):
	lint-imports --config $@
```

**Comment by seddonym** [comment]
Hi everyone,

Import Linter now supports multiple root packages. This means you can do things like this.

```
[importlinter]
root_packages=
    high
    medium
    low

[importlinter:contract:1]
name = My three-tier layers contract (multiple root packages)
type = layers
layers=
    high
    medium
    low
```

Hopefully this allows you all to do what you're trying to do. Let me know how it goes!

**Comment by proofit404** [comment]
Thanks!

**Comment by QasimK** [comment]
Thanks @seddonym! I hope to test this soon!
