### ISSUE TITLE
Forbid transitive imports

### ISSUE THREAD

**Issue by sobolevn** [seddonym/import-linter#54]
Hi! 

I am thing about if this is on scope of this project.
I really dislike transitive imports in my projects.

Like:

```python
# module.py
from a import b
```

And then:

```python
from module import b  # ???
```

What do you think about it?

**Comment by seddonym** [comment]
Hi Nikita,

Interesting - I hadn't anticipated this use case.

The [Grimp-backed](https://grimp.readthedocs.io/en/v1.0b12/usage.html#building-the-graph) graph that Import Linter uses doesn't currently give enough information to determine whether or not an import is transitive. All it will tell you is that A imports B, and B imports C. It does [give you the line contents](https://grimp.readthedocs.io/en/v1.0b12/usage.html#ImportGraph.get_import_details) which might help.

My feeling is that the underlying library (Grimp) would need to be rethought a bit in order to support this - feel free to open an issue / propose a PR on that project if you think it's worthwhile.

You could also experiment with writing your own custom contract which does some additional static analysis to figure out when this is going on.

My sense is that at the moment it's not quite right for core Import Linter, so I'm going to close the issue, but I'm willing to have my mind changed in the future.

**Comment by sobolevn** [comment]
It would be awesome to have this contract. Something like this:

```ini
[importlinter:contract:no-transitive]
name = Forbids to import anything from transitive modules
type = transitive

source = 
  wemake_python_styleguide
```

It really helps to untangle your module dependencies and forces you to refactor better. I know that my project contains a lot of transitive imports, but I just can't find them by my eyes. 

Sadly, that it is not on the roadmap. I hope that other users will support me here: it should be! 🙂 

(For anyone interested in this, please, put 👍 icon to this reply)

**Comment by seddonym** [comment]
Thanks for the follow up! In view of the 👍 s, I'll reopen the issue... I'd be happy to consider pull requests (they probably need to be on Grimp to begin with).

**Comment by sobolevn** [comment]
Mypy now has `implicit_reexport = False`, so this can be closed.

**Comment by seddonym** [comment]
Great, thanks @sobolevn!
