### ISSUE TITLE
Contracts on source code and tests

### ISSUE THREAD

**Issue by sobolevn** [seddonym/import-linter#55]
Hi, @seddonym! Thanks for this package once again 🙂 

I try to achieve the following:
1. Source code cannot import anything from `tests/`
2. Anything inside `tests/` directory cannot import from `tests/` as well

By doing this I try to encourage people to use `pytest` with its fixtures and plugins approach.

Currently I have this configuration:

```ini
[importlinter]
root_package = wemake_python_styleguide
include_external_packages = True

[importlinter:contract:tests-restrictions]
name = Explicit import restrictions for tests
type = forbidden

source_modules =
  wemake_python_styleguide
  tests

forbidden_modules =
  tests
```

But, it does not work as I want it to work:

```
» lint-imports
Module 'tests' does not exist.
```

What can this be achieved? Thanks again.
Original issue: https://github.com/wemake-services/wemake-python-styleguide/issues/720

**Comment by seddonym** [comment]
Hi @sobolevn,

Thanks for the issue!

Currently, it should be possible to achieve your first aim (Source code cannot import anything from tests). However, I'm afraid the second aim (Anything inside tests/ directory cannot import from tests/ as well) is not currently possible, at least in the same configuration. This is because import linter only builds the graph for one top-level package, it doesn't support analysing multiple top level packages. I do intend to support that at some point, and there is an open issue here: https://github.com/seddonym/import-linter/issues/43

In the meantime, you might be able to do a workaround by creating a separate configuration file with `tests` as the root package, with its own contract. You could then run `lint-imports` twice, one for your main configuration and one for the alternative configuration file.

Hope that helps.

**Comment by sobolevn** [comment]
@seddonym sounds like a plan. But, it does not work for me for some reason.

Here's the configuration I use for tests:
```ini
[importlinter]
root_package = tests
include_external_packages = True


[importlinter:contract:tests-restrictions1]
name = Explicit import restrictions for tests
type = forbidden

source_modules =
  tests

forbidden_modules =
  tests
```

Here's the screenshot with the regular import config and the tests' one:
<img width="752" alt="Снимок экрана 2019-07-29 в 17 52 52" src="https://user-images.githubusercontent.com/4660275/62058309-ebbdd280-b229-11e9-8c9e-b749b1981ab2.png">

Nothing happens, no output is shown, just error code `1`.

**Comment by seddonym** [comment]
Hmm, that's strange that you're not seeing an error. If I run that, I get the error "Modules have shared descendants."

I've created an issue for the lack of output here: https://github.com/seddonym/import-linter/issues/57.

In terms of your contract, I'm afraid I made a mistake - this kind of contract isn't currently supported for forbidden contracts. I've made an issue here: https://github.com/seddonym/import-linter/issues/58.
